import React, { useEffect, useState } from 'react';
import { DataTable } from '../../../global';
import { tournamentService } from '../../../../services';
import TournamentTeamModal from './TournamentTeamModal';
import checkMarkIcon from '../../../../assets/img/checkmark.png';

const TournamentRegisteredPlayersList = ({ tournamentId, tournamentType }) => {
  const [registeredTeams, setRegisteredTeams] = useState([]);
  const [selectedTeam, setSelectedTeam] = useState(null);

  //Below is a vector graphic of a checkmark. This was generated by AI. Could/should be replaced with a simpler implementation.
  const CheckMark = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
      <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.44z"/>
    </svg>
  );

  useEffect(() => {
    const fetchRegisteredTeams = async () => {
      const teams = await tournamentService.getRegisteredPlayers(tournamentId);
      setRegisteredTeams(teams);
    };

    fetchRegisteredTeams();
  }, [tournamentId]);

  const handleTeamNameClick = (team) => {
    setSelectedTeam(team);
  };

  const renderTeamNameCell = (team) => (
<button onClick={() => handleTeamNameClick(team)} style={{ cursor: 'pointer', background: 'none', border: 'none', textDecoration: 'underline' }}>
          {team.teamName}
        </button>
  );
  
    const columns = tournamentType === 'SingleZ' ? [
      {
        field: 'first_name', 
        headerName: 'Name', 
        renderCell: (row) => <>
          {row.membersDetails[0]?.username || 'N/A'}
        </>
      },
      {
        field: 'zenemy', 
        headerName: 'Zenemy', 
        renderCell: (row) => row[0]?.zenemy ? <CheckMark />  : '-'
      },
      {
        field: 'checkedIn', 
        headerName: 'Checked In', 
        renderCell: (row) => row.membersDetails[0]?.checkedIn ? <CheckMark /> : '-'
      },
    ] : [
      {
        field: 'teamName', 
        headerName: 'Team Name', 
        renderCell: (row) => renderTeamNameCell(row)
      },
      {
        field: 'checkedIn', 
        headerName: 'Checked In', 
        // Assuming a team is checked in if any of its members are checked in
        renderCell: (row) => <CheckMark />
      },
    ];
return (
  <>
          <h3 className="sovjet-section-heading">Registered Teams: {registeredTeams.length}</h3>
    <DataTable columns={columns} data={registeredTeams} hideColumnsOnMobile={['']} />
    {selectedTeam && (
      <TournamentTeamModal
        team={selectedTeam}
        show={!!selectedTeam} // Pass show prop based on selectedTeam state
        onClose={() => setSelectedTeam(null)}
      />
    )}
  </>
);
};

export default TournamentRegisteredPlayersList;
